Controllers/AgregarController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;

namespace Tarjetero_Virtual.Controllers
{
    public class AgregarController : Controller
    {
        // GET: AgregarController
        public ActionResult Index()
        {
            return View();
        }

        // GET: AgregarController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AgregarController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AgregarController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AgregarController/Edit/5
        public ActionResult Save(string tar_dueño, string tar_banco, string tar_emisor, string tar_numerotarjeta, string tar_ccv, string tar_fechaexpiracion, string tar_estado, IFormFile tar_fotobanco, IFormFile tar_fotoemisor, IFormFile tar_fotofondo)
        {
            string filePath1;
            string filePath2;
            string filePath3;
            if (tar_fotobanco != null && tar_fotoemisor != null && tar_fotofondo != null)
            {
                string fileName = tar_banco + new FileInfo(tar_fotobanco.FileName).Extension;
                filePath1 = Path.Combine("Imagenes/Bancos/", fileName);
                string localFileName = Path.Combine(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Imagenes/Bancos"), fileName);

                string fileName1 = tar_fotoemisor + new FileInfo(tar_fotoemisor.FileName).Extension;
                filePath2 = Path.Combine("Imagenes/Emisor/", fileName1);
                string localFileName1 = Path.Combine(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Imagenes/Emisor"), fileName1);

                string fileName2 = tar_fotofondo + new FileInfo(tar_fotofondo.FileName).Extension;
                filePath3 = Path.Combine("Imagenes/Fondosdetarjetas/", fileName2);
                string localFileName2 = Path.Combine(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Imagenes/Fondosdetarjetas"), fileName2);

                using (var stream = new FileStream(localFileName2, FileMode.Create))
                {
                    tar_fotofondo.CopyTo(stream);
                };


            }
            else
            {
                filePath1 = Path.Combine("Imagenes/Bancos/", tar_banco + ".png");
                filePath2 = Path.Combine("Imagenes/Emisores/", tar_emisor + ".png");
                filePath3 = Path.Combine("Imagenes/Fondosdetarjetas/", "default.png");
            }
            List<SqlParameter> param = new List<SqlParameter>()
            {
                new SqlParameter("@tar_dueño", tar_dueño),
                new SqlParameter("@tar_banco", tar_banco),
                new SqlParameter("@tar_emisor", tar_emisor),
                new SqlParameter("@tar_numerotarjeta", tar_numerotarjeta),
                new SqlParameter("@tar_ccv", tar_ccv),
                new SqlParameter("@tar_fechaexpiracion", tar_fechaexpiracion),
                new SqlParameter("@tar_estado", tar_estado),
                new SqlParameter("@tar_fotobanco", filePath1),
                new SqlParameter("@tar_fotoemisor", filePath2),
                new SqlParameter("tar_fotofondo", filePath3)
            };

            Database.DatabaseHelper.ExecStoreProcedure("sp_insert_tarjetas", param);


            return RedirectToAction("Index", "Home");
        }

        // POST: AgregarController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AgregarController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AgregarController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
@*@{

    ViewBag.Title = "tarjetas";
}*@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tarjetero_Virtual</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Tarjetero_Virtual.styles.css" asp-append-version="true" />
</head>
 <header class="header">
      <nav class="navbar navbar-light bg-white box-shadow justify-content-center align-items-center h-100">
                <a class="navbar" style="margin-right:65px" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Imagenes/Iconos/tarjetas.png" style="width:40px; height:40px" /> </a>
                <div class="navbar">
                    <h4><label>TUS TARJETAS</label></h4>
                    <ul class="navbar-nav">
                        <li class="nav-item" style="margin-left:65px">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Agregar" asp-action="Index"><img src="~/Imagenes/Iconos/agregar.png" style="width:40px; height:40px" /></a>
                        </li>
                    </ul>
                </div>
        </nav>
</header>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</body>
 <footer class="footer">
     
       <nav class="navbar navbar-light sticky-lg-top bg-white box-shadow justify-content-center align-items-center" style="height:102px">
         @using (Html.BeginForm("buscar_tarjetas", "Home", FormMethod.Get))
            {
                    <div class="row">
                       <div class="col-9">
                           <input type="text" class="form-control" id="bancoxemisor" name="bancoxemisor" placeholder="">
                       </div>
                       <div class="col-3">
                       <button type="submit" class="btn btn-outline-info" style="float:right">Buscar</button>
                       </div>
                  </div>
            }
            
        </nav>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</html>