Controllers/EditarController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;
using Tarjetero_Virtual.Models;

namespace Tarjetero_Virtual.Controllers
{
    public class EditarController : Controller
    {
        // GET: EditarController
        public ActionResult Index(int tar_id)
        {
            ViewBag.Tarjeta = load_Tarjeta(tar_id);
            return View();
        }
        private List<TarjetaModel> load_Tarjeta(int tar_id)
        {
            List<SqlParameter> param = new List<SqlParameter>()
            {
                new SqlParameter("@tar_id", tar_id)
            };
            DataTable ds = Database.DatabaseHelper.ExecuteStoreProcedure("sp_select_tarjeta", param);
            List<TarjetaModel> tarjetaList = new List<TarjetaModel>();

            foreach (DataRow row in ds.Rows)
            {
                tarjetaList.Add(new TarjetaModel()
                {
                    tar_id = Convert.ToInt16(row["id"]),
                    tar_dueño = row["dueño"].ToString(),
                    tar_numerotarjeta = row["numerotarjeta"].ToString(),
                    tar_fechaexpiracion = row["fechaexpiracion"].ToString()
                });
            }

            return tarjetaList;
        }

        public ActionResult Update_tarjeta(int id, string tar_dueño, string tar_numerotarjeta , string tar_fechaexpiracion)
        {
            List<SqlParameter> param = new List<SqlParameter>()
            {
                new SqlParameter("@tar_id", id),
                new SqlParameter("@tar_dueño", tar_dueño),
                new SqlParameter("@tar_numerotarjeta", tar_numerotarjeta),
                new SqlParameter("@tar_fechaexpiracion", tar_fechaexpiracion)
            };

            Database.DatabaseHelper.ExecStoreProcedure("sp_update_tarjeta", param);

            return RedirectToAction("Index", "Home");
        }
        // GET: EditarController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EditarController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EditarController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EditarController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: EditarController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EditarController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: EditarController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Editar/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://fonts.googleapis.com/css?family=Lato|Liu+Jian+Mao+Cao&display=swap" rel="stylesheet">
</head>


<div class="container d-flex justify-content-center align-items-center h-100" style="">
                @foreach (var item in @ViewBag.Tarjeta){
                    <form method="post" action="@Url.Action("Update_tarjeta", "Editar")" enctype="multipart/form-data">
                             <div class="card">
                                <div class="card-header">
                                   <h5 class="mb-0"><b>Editar Tarjeta</b></h5>
                                    </div>
                                    <div class="card-body">
                                        <input hidden="hidden" name="id" value="@item.tar_id">
                                        <div class="form-outline mb-2">
                                            <input type="text" value="@item.tar_dueño" id="tar_dueño" name="tar_dueño" class="form-control" required />
                                            <label class="form-label" for="tar_dueño">Dueño:</label>
                                        </div>
                                    
                                        <div class="form-outline mb-2">
                                            <input type="text" id="tar_numerotarjeta" value="@item.tar_numerotarjeta" name="tar_numerotarjeta" class="form-control" required />
                                            <label class="form-label" for="tar_numerotarjeta">Número de tarjeta:</label>
                                        </div>
                                      <div class="form mb-2">
                                        <input type="date" id="tar_fechaexpiracion" class="form-control" value="@item.tar_fechaexpiracion" name="tar_fechaexpiracion" placeholder="date">
                                    </div>
                                    </div>
                                     <div class="card-footer">
                                        <button type="submit" class="btn btn-success" style="float:right"><b>Guardar</b></button>
                            </div>
                    </form>

                    }
                    
 </div>
                    